import { Router, type IRouter } from "express";

const router: IRouter = Router();

router.get("/home", async (req, res): Promise<void> => {
  res.json({
    banners: [
      {
        id: "b1",
        title: "Frete Grátis em Chapecó",
        subtitle: "Para compras acima de R$ 79",
        imageUrl: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
        linkUrl: "/listing",
        badgeText: "FRETE GRÁTIS",
      },
      {
        id: "b2",
        title: "Moda Verão 2025",
        subtitle: "Até 60% de desconto",
        imageUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80",
        linkUrl: "/listing?category=moda",
        badgeText: "ATÉ 60% OFF",
      },
      {
        id: "b3",
        title: "Eletrônicos com Pix",
        subtitle: "10% de desconto no Pix",
        imageUrl: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&q=80",
        linkUrl: "/listing?category=eletronicos",
        badgeText: "PIX -10%",
      },
    ],
    categories: [
      { id: "cat1", name: "Moda", slug: "moda", icon: "shirt", productCount: 342 },
      { id: "cat2", name: "Delivery", slug: "delivery", icon: "bike", productCount: 87 },
      { id: "cat3", name: "Eletrônicos", slug: "eletronicos", icon: "smartphone", productCount: 215 },
      { id: "cat4", name: "Móveis", slug: "moveis", icon: "sofa", productCount: 128 },
      { id: "cat5", name: "Serviços", slug: "servicos", icon: "wrench", productCount: 64 },
      { id: "cat6", name: "Mercado", slug: "mercado", icon: "shopping-cart", productCount: 891 },
      { id: "cat7", name: "Farmácia", slug: "farmacia", icon: "pill", productCount: 203 },
      { id: "cat8", name: "Esportes", slug: "esportes", icon: "dumbbell", productCount: 156 },
    ],
    featuredProducts: [
      {
        id: "p1",
        name: "Tênis Esportivo Air Run Pro",
        description: "Tênis de corrida com tecnologia de amortecimento avançada",
        price: 189.90,
        originalPrice: 299.90,
        discountPct: 37,
        imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80"],
        category: "Esportes",
        categorySlug: "esportes",
        vendorId: "v1",
        vendorName: "SportCO Chapecó",
        vendorLogoUrl: null,
        rating: 4.8,
        reviewCount: 234,
        salesCount: 1204,
        stock: 42,
        isFavorited: false,
        sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
        deliveryDays: 2,
        freeShipping: true,
      },
      {
        id: "p2",
        name: "Smartphone Samsung Galaxy A55",
        description: "128GB, 6GB RAM, câmera 50MP, tela AMOLED 6.6\"",
        price: 1649.00,
        originalPrice: 1999.00,
        discountPct: 18,
        imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&q=80",
        images: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80"],
        category: "Eletrônicos",
        categorySlug: "eletronicos",
        vendorId: "v2",
        vendorName: "TechStore Chape",
        vendorLogoUrl: null,
        rating: 4.7,
        reviewCount: 512,
        salesCount: 2890,
        stock: 15,
        isFavorited: true,
        sizes: null,
        deliveryDays: 1,
        freeShipping: true,
      },
    ],
    carousels: [
      {
        category: { id: "cat1", name: "Moda", slug: "moda", icon: "shirt", productCount: 342 },
        products: [
          {
            id: "p3",
            name: "Vestido Floral Verão",
            description: "Vestido leve, perfeito para o calor chapecoense",
            price: 79.90,
            originalPrice: 129.90,
            discountPct: 38,
            imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&q=80",
            images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80"],
            category: "Moda",
            categorySlug: "moda",
            vendorId: "v3",
            vendorName: "Boutique Bella CO",
            vendorLogoUrl: null,
            rating: 4.6,
            reviewCount: 89,
            salesCount: 445,
            stock: 28,
            isFavorited: false,
            sizes: ["P", "M", "G", "GG"],
            deliveryDays: 3,
            freeShipping: false,
          },
          {
            id: "p4",
            name: "Camisa Social Slim Fit",
            description: "Camisa masculina 100% algodão, corte slim",
            price: 89.90,
            originalPrice: null,
            discountPct: null,
            imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&q=80",
            images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80"],
            category: "Moda",
            categorySlug: "moda",
            vendorId: "v4",
            vendorName: "Moda Masculina SC",
            vendorLogoUrl: null,
            rating: 4.5,
            reviewCount: 67,
            salesCount: 312,
            stock: 19,
            isFavorited: false,
            sizes: ["P", "M", "G", "GG", "XGG"],
            deliveryDays: 3,
            freeShipping: true,
          },
          {
            id: "p5",
            name: "Tênis Casual Feminino",
            description: "Confortável e estiloso para o dia a dia",
            price: 159.90,
            originalPrice: 199.90,
            discountPct: 20,
            imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80",
            images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800&q=80"],
            category: "Moda",
            categorySlug: "moda",
            vendorId: "v3",
            vendorName: "Boutique Bella CO",
            vendorLogoUrl: null,
            rating: 4.7,
            reviewCount: 145,
            salesCount: 678,
            stock: 33,
            isFavorited: true,
            sizes: ["35", "36", "37", "38", "39", "40"],
            deliveryDays: 2,
            freeShipping: true,
          },
        ],
      },
      {
        category: { id: "cat6", name: "Mercado", slug: "mercado", icon: "shopping-cart", productCount: 891 },
        products: [
          {
            id: "p6",
            name: "Cesta Básica Completa",
            description: "17 itens essenciais de qualidade selecionados",
            price: 149.90,
            originalPrice: 189.90,
            discountPct: 21,
            imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&q=80",
            images: ["https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80"],
            category: "Mercado",
            categorySlug: "mercado",
            vendorId: "v5",
            vendorName: "Supermercado Nobre",
            vendorLogoUrl: null,
            rating: 4.4,
            reviewCount: 203,
            salesCount: 1567,
            stock: 100,
            isFavorited: false,
            sizes: null,
            deliveryDays: 1,
            freeShipping: true,
          },
          {
            id: "p7",
            name: "Kit Café Premium",
            description: "Café Serra do Chapecó moído 500g + açúcar orgânico",
            price: 34.90,
            originalPrice: null,
            discountPct: null,
            imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&q=80",
            images: ["https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80"],
            category: "Mercado",
            categorySlug: "mercado",
            vendorId: "v5",
            vendorName: "Supermercado Nobre",
            vendorLogoUrl: null,
            rating: 4.9,
            reviewCount: 312,
            salesCount: 2103,
            stock: 200,
            isFavorited: false,
            sizes: null,
            deliveryDays: 1,
            freeShipping: false,
          },
        ],
      },
      {
        category: { id: "cat3", name: "Eletrônicos", slug: "eletronicos", icon: "smartphone", productCount: 215 },
        products: [
          {
            id: "p2",
            name: "Smartphone Samsung Galaxy A55",
            description: "128GB, 6GB RAM, câmera 50MP",
            price: 1649.00,
            originalPrice: 1999.00,
            discountPct: 18,
            imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&q=80",
            images: ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80"],
            category: "Eletrônicos",
            categorySlug: "eletronicos",
            vendorId: "v2",
            vendorName: "TechStore Chape",
            vendorLogoUrl: null,
            rating: 4.7,
            reviewCount: 512,
            salesCount: 2890,
            stock: 15,
            isFavorited: true,
            sizes: null,
            deliveryDays: 1,
            freeShipping: true,
          },
          {
            id: "p8",
            name: "Fone de Ouvido Bluetooth",
            description: "Som HD, 30h de bateria, cancelamento de ruído",
            price: 199.90,
            originalPrice: 299.90,
            discountPct: 33,
            imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
            images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80"],
            category: "Eletrônicos",
            categorySlug: "eletronicos",
            vendorId: "v2",
            vendorName: "TechStore Chape",
            vendorLogoUrl: null,
            rating: 4.6,
            reviewCount: 278,
            salesCount: 1432,
            stock: 38,
            isFavorited: false,
            sizes: null,
            deliveryDays: 2,
            freeShipping: true,
          },
        ],
      },
    ],
    flashDeals: [
      {
        id: "p9",
        name: "Mochila Escolar Reforçada",
        description: "Impermeável, 35 litros, compartimento notebook",
        price: 89.90,
        originalPrice: 179.90,
        discountPct: 50,
        imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80",
        images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80"],
        category: "Esportes",
        categorySlug: "esportes",
        vendorId: "v1",
        vendorName: "SportCO Chapecó",
        vendorLogoUrl: null,
        rating: 4.5,
        reviewCount: 156,
        salesCount: 892,
        stock: 7,
        isFavorited: false,
        sizes: null,
        deliveryDays: 2,
        freeShipping: true,
      },
    ],
  });
});

export default router;
