import { Router, type IRouter } from "express";
import healthRouter from "./health";
import homeRouter from "./home";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import ordersRouter from "./orders";
import cartRouter from "./cart";
import couponsRouter from "./coupons";
import feedRouter from "./feed";
import favoritesRouter from "./favorites";
import profileRouter from "./profile";
import authRouter from "./auth";
import freteRouter from "./frete";
import disputesRouter from "./disputes";
import storesRouter from "./stores";
import productQuestionsRouter from "./productQuestions";
import coinsRouter from "./coins";
import reviewsRouter from "./reviews";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(homeRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(cartRouter);
router.use(couponsRouter);
router.use(feedRouter);
router.use(favoritesRouter);
router.use(profileRouter);
router.use(freteRouter);
router.use(disputesRouter);
router.use(storesRouter);
router.use(productQuestionsRouter);
router.use(coinsRouter);
router.use(reviewsRouter);

export default router;
